#!/usr/bin/env bash

# With ideas from: 
# https://github.com/seebi/dircolors-solarized

SCHEME=$1
dir=$(dirname "$0")
scheme_dir=$dir/../gnome-colors/$SCHEME

if [ ! -d "${scheme_dir}" ] ; then
	echo "Invalid profile. Choose Light or Dark"
	exit;
fi	

dircolors_file="${HOME}/.config/dotfiles/dircolors"
cp $scheme_dir/dircolors ${dircolors_file}-$SCHEME
ln -sf  ${dircolors_file}-$SCHEME ${dircolors_file}

eval `dircolors ${dircolors_file}`

#
# Demo
#
if [ ! -d "/tmp/dircolors-solarized-demo" ] ; then 
	mkdir -p /tmp/dircolors-solarized-demo
	sudo tar xfj $dir/support/test-directory.tar.bz2 -C /tmp/dircolors-solarized-demo
fi

command ls --color /tmp/dircolors-solarized-demo/test-directory