#!/usr/bin/env bash

# With ideas from: 
#   https://github.com/aruhier/gnome-terminal-colors-solarized
#   https://github.com/coolwanglu/guake-colors-solarized

SCHEME=$1
dir=$(dirname "$0")
scheme_dir=$dir/../gnome-colors/$SCHEME
show_sample='OFF'

if [ ! -d "${scheme_dir}" ] ; then
	echo "Invalid profile. Choose Light or Dark"
	exit;
fi

function to_dconf() {
    tr '\n' '~' | sed -e "s#~\$#']\n#" -e "s#~#', '#g" -e "s#^#['#"
}


function setup_gnome_terminal() {
	profile=$(gsettings get org.gnome.Terminal.ProfilesList default)
	profile_id=${profile:1:-1} 
	profile_name=$(gsettings get "org.gnome.Terminal.Legacy.Profile:/org/gnome/terminal/legacy/profiles:/:$profile_id/" visible-name)

	dconfdir=/org/gnome/terminal/legacy/profiles:
	profile_path="$dconfdir/:$profile_id"


	# set color palette
	dconf write $profile_path/palette "$(to_dconf < $scheme_dir/palette)"

	# set foreground, background and highlight color
	dconf write $profile_path/bold-color       "'$(cat $scheme_dir/bd_color)'"
	dconf write $profile_path/background-color "'$(cat $scheme_dir/bg_color)'"
	dconf write $profile_path/foreground-color "'$(cat $scheme_dir/fg_color)'"

	# make sure the profile is set to not use theme colors
	dconf write $profile_path/use-theme-colors "false"

	# set highlighted color to be different from foreground color
	dconf write $profile_path/bold-color-same-as-fg "false"


	# Transparency
	dconf write $profile_path/use-theme-transpareny  "false"
	dconf write $profile_path/background-transparency-percent "5"
}


function setup_tilix_terminal() {
	profile=$(gsettings get com.gexperts.Tilix.ProfilesList default)
	profile_id=${profile:1:-1} 

	dconfdir=/com/gexperts/Tilix/profiles
	profile_path="$dconfdir/$profile_id"

	#dconf dump "$profile_path/"

	# set color palette
	dconf write $profile_path/palette "$(to_dconf < $scheme_dir/palette)"

	# set foreground, background and highlight color
	dconf write $profile_path/bold-color       "'$(cat $scheme_dir/bd_color)'"
	dconf write $profile_path/bold-color-set   "true"
	dconf write $profile_path/allow-bold       "true"
	dconf write $profile_path/bold-is-bright   "true"
	
	dconf write $profile_path/background-color "'$(cat $scheme_dir/bg_color)'"
	dconf write $profile_path/foreground-color "'$(cat $scheme_dir/fg_color)'"


	dconf write $profile_path/badge-color     "'$(cat $scheme_dir/fg_color)'"
	dconf write $profile_path/badge-color-set "true"

	# make sure the profile is set to not use theme colors
	dconf write $profile_path/use-theme-colors "false"

	# Transparency
	dconf write $profile_path/use-theme-transpareny  "false"
	dconf write $profile_path/background-transparency-percent "5"
}


function setup_quake_terminal() {
	# Guake
	guake_str=$(cat $scheme_dir/guake)
	dconf write "/apps/guake/style/font/palette" "'$guake_str'"
	dconf write "/apps/guake/style/font/palette-name" "'Solarized: $SCHEME'"
}


function setup_alacritty_terminal(){
	mkdir -p ~/.config/alacritty/
	cp $scheme_dir/alacritty.yml ${HOME}/.config/alacritty/alacritty-$SCHEME.yml
	ln -sf ${HOME}/.config/alacritty/alacritty-$SCHEME.yml ${HOME}/.config/alacritty/alacritty.yml
}

setup_gnome_terminal
setup_tilix_terminal
setup_quake_terminal
setup_alacritty_terminal

if [[ "$show_sample" == "ON" ]]; then
	#apt install colortest
	if [ -x "$(command -v colortest-8)" ] ; then
		colortest-8
	fi
fi

exit
echo  "Please note that there is no uninstall option yet. If you do not "
echo  "wish to overwrite any of your profiles, you should create a new "
echo  "profile before you run this script. However, you can reset your "
echo  "colors to the Gnome default, by running:"
echo "    dconf reset -f /org/gnome/terminal/legacy/profiles:/"