#!/usr/bin/env bash

SCHEME=$1
dir=$(dirname "$0")
scheme_dir=$dir/../gnome-colors/$SCHEME


if [ ! -d "${scheme_dir}" ] ; then
	echo "Invalid profile. Choose Light or Dark"
	exit;
fi	


cp $scheme_dir/Xresources ${HOME}/.config/dotfiles/Xresources-$SCHEME
ln -sf ${HOME}/.config/dotfiles/Xresources-$SCHEME ~/.Xresources
xrdb -merge ~/.Xresources

# MC
cp $scheme_dir/mc.ini ${HOME}/.config/dotfiles/mc-$SCHEME.ini
ln -sf ${HOME}/.config/dotfiles/mc-$SCHEME.ini ${HOME}/.config/dotfiles/mc.ini