#!/bin/bash
dir=$(dirname "$0")
menuitem=$1

if [[ "${menuitem}" == "" ]]; then 
	INPUT=/tmp/menu.sh.$$
	dialog  --title "[Solarize System]" \
			--menu "Choose solarized theme:" 15 50 4   \
	        "Dark"  "Use Solarized Dark Theme"  \
	        "Light" "Use Solarized Light Theme" \
	        "Exit"  "Don't change anything" 2>"${INPUT}"
	menuitem=$(<"${INPUT}")

	# Clear Screen
	tput reset
fi

[[ "$menuitem" == "Exit" ]] && exit

scheme_dir=$dir/gnome-colors/$menuitem
if [ ! -d "${scheme_dir}" ] ; then
	echo "Invalid profile. Choose Light or Dark"
	exit;
fi

# copy dotfiles
mkdir -p ${HOME}/.config/dotfiles/
cp -r ./shell ${HOME}/.config/dotfiles/

$dir/setup-gnome-terminal $menuitem
$dir/setup-dir-colors     $menuitem

